
name: Domain DeÄŸiÅŸiklik KontrolÃ¼

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '25 */6 * * *'

jobs:
  DomainKontrol:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Depoyu Ã‡ek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Python SÃ¼rÃ¼mÃ¼nÃ¼ GÃ¶ster
        run: python --version

      - name: Gereksinimleri YÃ¼kle
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cloudscraper pycryptodome

      - name: BetiÄŸi Ã‡alÄ±ÅŸtÄ±r
        run: python KONTROL.py

      - name: Commit ve Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A

          # EÄŸer deÄŸiÅŸiklik yoksa workflow fail etmesin
          if git diff --cached --quiet; then
            echo "DeÄŸiÅŸiklik yok"
            exit 0
          fi

          git commit -m "ðŸ¤– Domain Update" -m "Automatic domain update"
          git push
